# commitments.py - Pedersen-style commitments C=bG+rH(modp)
#secrets provide cryptographically secure random number
import secrets

# public params
p = 2**127 - 1 # fixed large prime not a secret 2^127 − 1 
#pick a random number that is from 1 to p-1 for G
G = secrets.randbelow(p-1) + 1
#pick a random number that is from 1 to p-1 for H
H = secrets.randbelow(p-1) + 1
#make sure that H and G are not equal numbers as it checks if they are equal it generates a new H 
while H == G:
    H = secrets.randbelow(p-1) + 1
#generate commitment parameters returns the global values variables in this function
def generate_commitment_params():
    return {"p": p, "G": G, "H": H}

#creating the pedersen commitment that will allow us to hide our values 
#takes in as a parameter the bid and has no parameters or randomness 
def commit_bid(bid, randomness=None, params=None):
    if params is None: #checks if the value of the params is none(it is) it will take the values generated by the global variables
    #using the generate commitment params
        params = generate_commitment_params()
    p = params["p"] #extracting the p from the generate_commitment_params return 
    G = params["G"] #extracting the g from the generate_commitment_params return 
    H = params["H"] #extracting the h from the generate_commitment_params return 
    if randomness is None:  #checks if randomness is none (it is) to generate the random number 
        randomness = secrets.randbelow(p-1) + 1
        #C = b*g + r*p mod p 
    commitment = ((bid % p) * G + (randomness % p) * H) % p #creates the pedersen commitment
    #does the bid and the randomness mod p first to make sure they are inside the mod 
    return commitment, randomness #return the commitment (C) and the random value (R)

#verify the commitment
def verify_commitment(bid, randomness, commitment, params=None):
    if params is None:# if params = none takes the p,g,h again and recomputes the same formula and checks if they are equal than it is verified
        params = generate_commitment_params()
    p = params["p"]
    G = params["G"]
    H = params["H"]
    recomputed = ((bid % p) * G + (randomness % p) * H) % p
    return recomputed == commitment
